version: '3.4'


networks:
  simple-crud-ntw:
    external: true
    driver: bridge

volumes:
  sc-postgres-db:

services:
  sc-postgres:
    image: postgres:11
    container_name: ${APP_NAME}-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      POSTGRES_USER_NAME: ${POSTGRES_USER_NAME}
      POSTGRES_USER_PASSWORD: ${POSTGRES_USER_PASSWORD}
      POSTGRES_USER_DB: ${POSTGRES_USER_DB}
      PGUSER: ${POSTGRES_ADMIN_USER}
      PGPASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      PGDATABASE: ${POSTGRES_USER_DB}
    volumes:
      - sc-postgres-db:/var/lib/postgresql/data
      - ./.build/postgres/bash:/docker-entrypoint-initdb.d:rw
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
    networks:
      simple-crud-ntw:

      