version: '3.4'

networks:
  simple-crud-ntw:
    external: true
    driver: bridge

services:
  api-gateway-integration-tests:
    image: ${DOCKER_REGISTRY-}${APP_NAME}.${API_GATEWAY_SERVICE_NAME}-integration-tests
    build:
      context: ../Services/Api.Gateway/Api.Gateway.Test.Integration
      dockerfile: Dockerfile
      labels:
        - app.name=${APP_NAME}  
    container_name: ${APP_NAME}.${API_GATEWAY_SERVICE_NAME}-integration-tests
    environment:
      - TestConfig__ServiceHost=http://${API_GATEWAY_SERVICE_NAME}
    networks:
      simple-crud-ntw:
