version: '3.4'

networks:
  simple-crud-ntw:
    external: true
    driver: bridge

services:
  api-gateway-integration-tests:
    image: ${DOCKER_REGISTRY-}${APP_NAME}.${GIS_SERVICE_NAME}-integration-tests
    build:
      context: ../Services/Gis/Gis.Test.Integration
      dockerfile: Dockerfile
      labels:
        - app.name=${APP_NAME}  
    container_name: ${APP_NAME}.${GIS_SERVICE_NAME}-integration-tests
    environment:
      - TestConfig__ServiceHost=http://${GIS_SERVICE_NAME}
    networks:
      simple-crud-ntw:
