// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Person.Model;

namespace Person.Model.Migrations
{
    [DbContext(typeof(PersonDbContext))]
    [Migration("20210513025611_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Person")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Person.Model.Entity.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "г Новосибирск",
                            Email = "Bonnie_Bode83@yahoo.com",
                            FirstName = "Игнат",
                            LastName = "Лебедев",
                            PhoneNumber = "79166113768",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "11791"
                        },
                        new
                        {
                            Id = 2,
                            City = "г Новосибирск",
                            Email = "Elroy.Harvey@gmail.com",
                            FirstName = "Николай",
                            LastName = "Зуева",
                            PhoneNumber = "79256060675",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "30120"
                        },
                        new
                        {
                            Id = 3,
                            City = "г Новосибирск",
                            Email = "Conner5@hotmail.com",
                            FirstName = "Даниил",
                            LastName = "Крылов",
                            PhoneNumber = "79106585034",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "11791"
                        },
                        new
                        {
                            Id = 4,
                            City = "г Новосибирск",
                            Email = "Anderson_Huels@gmail.com",
                            FirstName = "Григорий",
                            LastName = "Сыромятникова",
                            PhoneNumber = "79206398166",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "11791"
                        },
                        new
                        {
                            Id = 5,
                            City = "г Новосибирск",
                            Email = "Emery_Kreiger@gmail.com",
                            FirstName = "Дамир",
                            LastName = "Рыжова",
                            PhoneNumber = "79152254604",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "48601"
                        },
                        new
                        {
                            Id = 6,
                            City = "г Новосибирск",
                            Email = "Anna24@hotmail.com",
                            FirstName = "Назар",
                            LastName = "Булыгина",
                            PhoneNumber = "79197853566",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "46304"
                        },
                        new
                        {
                            Id = 7,
                            City = "г Новосибирск",
                            Email = "Christa.Block@hotmail.com",
                            FirstName = "Давид",
                            LastName = "Койтасбаева",
                            PhoneNumber = "79301262016",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "11791"
                        },
                        new
                        {
                            Id = 8,
                            City = "г Новосибирск",
                            Email = "Anabelle_OConnell@hotmail.com",
                            FirstName = "Абдулька",
                            LastName = "Жарыхин",
                            PhoneNumber = "79122253313",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "48601"
                        },
                        new
                        {
                            Id = 9,
                            City = "г Новосибирск",
                            Email = "Arvel28@yahoo.com",
                            FirstName = "Авашерфа",
                            LastName = "Антимонова",
                            PhoneNumber = "79194399119",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "46304"
                        },
                        new
                        {
                            Id = 10,
                            City = "г Новосибирск",
                            Email = "Conner5@hotmail.com",
                            FirstName = "Авгалифена",
                            LastName = "Ягубова",
                            PhoneNumber = "79136963602",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "30120"
                        },
                        new
                        {
                            Id = 11,
                            City = "г Новосибирск",
                            Email = "Cecile.Herman8@hotmail.com",
                            FirstName = "Августа",
                            LastName = "Сыромятникова",
                            PhoneNumber = "79153536338",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "48601"
                        },
                        new
                        {
                            Id = 12,
                            City = "г Новосибирск",
                            Email = "Dakota34@hotmail.com",
                            FirstName = "Макар",
                            LastName = "Данильцина",
                            PhoneNumber = "79124496807",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "30120"
                        },
                        new
                        {
                            Id = 13,
                            City = "г Новосибирск",
                            Email = "Allie.Thompson24@gmail.com",
                            FirstName = "Авгиння",
                            LastName = "Чунц",
                            PhoneNumber = "79116488841",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "30120"
                        },
                        new
                        {
                            Id = 14,
                            City = "г Новосибирск",
                            Email = "Bethany62@gmail.com",
                            FirstName = "Абдулния",
                            LastName = "Ермолаева",
                            PhoneNumber = "79152254604",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "48601"
                        },
                        new
                        {
                            Id = 15,
                            City = "г Новосибирск",
                            Email = "Corrine_Toy@hotmail.com",
                            FirstName = "Эльвира",
                            LastName = "Ермолаева",
                            PhoneNumber = "79222998760",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "46304"
                        },
                        new
                        {
                            Id = 16,
                            City = "г Новосибирск",
                            Email = "Emery.Homenick@yahoo.com",
                            FirstName = "Кирилл",
                            LastName = "Лукьяненко",
                            PhoneNumber = "79222998760",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "11791"
                        },
                        new
                        {
                            Id = 17,
                            City = "г Новосибирск",
                            Email = "Fleta85@hotmail.com",
                            FirstName = "Абдупатта",
                            LastName = "Авилова",
                            PhoneNumber = "79214483093",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "11791"
                        },
                        new
                        {
                            Id = 18,
                            City = "г Новосибирск",
                            Email = "Deron71@hotmail.com",
                            FirstName = "Константин",
                            LastName = "Жикина",
                            PhoneNumber = "79135453084",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "11791"
                        },
                        new
                        {
                            Id = 19,
                            City = "г Новосибирск",
                            Email = "Brandon.Schimmel87@gmail.com",
                            FirstName = "Нона",
                            LastName = "Железнов",
                            PhoneNumber = "79206112248",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "11791"
                        },
                        new
                        {
                            Id = 20,
                            City = "г Новосибирск",
                            Email = "Claudia58@gmail.com",
                            FirstName = "Камиль",
                            LastName = "Богоявленская",
                            PhoneNumber = "79150056116",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "30120"
                        },
                        new
                        {
                            Id = 21,
                            City = "г Новосибирск",
                            Email = "Daniella22@yahoo.com",
                            FirstName = "Василий",
                            LastName = "Зуева",
                            PhoneNumber = "79170829045",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "48601"
                        },
                        new
                        {
                            Id = 22,
                            City = "г Новосибирск",
                            Email = "Bonnie_Bode83@yahoo.com",
                            FirstName = "Платон",
                            LastName = "Кравчиков",
                            PhoneNumber = "79256060675",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "11791"
                        },
                        new
                        {
                            Id = 23,
                            City = "г Новосибирск",
                            Email = "Ferne_Kuhlman@hotmail.com",
                            FirstName = "Игнат",
                            LastName = "Жуков",
                            PhoneNumber = "79118006386",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "11791"
                        },
                        new
                        {
                            Id = 24,
                            City = "г Новосибирск",
                            Email = "Fleta85@hotmail.com",
                            FirstName = "Абдурасуль",
                            LastName = "Ермолаева",
                            PhoneNumber = "79166113768",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "11791"
                        },
                        new
                        {
                            Id = 25,
                            City = "г Новосибирск",
                            Email = "Clarabelle66@gmail.com",
                            FirstName = "Абдюль",
                            LastName = "Богоявленская",
                            PhoneNumber = "79116488841",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "11791"
                        },
                        new
                        {
                            Id = 26,
                            City = "г Новосибирск",
                            Email = "Derrick.Koelpin@yahoo.com",
                            FirstName = "Олег",
                            LastName = "Ельчуков",
                            PhoneNumber = "79147692876",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "11791"
                        },
                        new
                        {
                            Id = 27,
                            City = "г Новосибирск",
                            Email = "Bonnie_Bode83@yahoo.com",
                            FirstName = "Абам",
                            LastName = "Коченков",
                            PhoneNumber = "79185574147",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "46304"
                        },
                        new
                        {
                            Id = 28,
                            City = "г Новосибирск",
                            Email = "Cathryn_Halvorson82@hotmail.com",
                            FirstName = "Савелий",
                            LastName = "Бурцева",
                            PhoneNumber = "79249669496",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "11791"
                        },
                        new
                        {
                            Id = 29,
                            City = "г Новосибирск",
                            Email = "Anderson_Huels@gmail.com",
                            FirstName = "Ева",
                            LastName = "Бархотов",
                            PhoneNumber = "79274932037",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "11791"
                        },
                        new
                        {
                            Id = 30,
                            City = "г Новосибирск",
                            Email = "Colin.Ferry@yahoo.com",
                            FirstName = "Авашарфа",
                            LastName = "Устимовича",
                            PhoneNumber = "79139023581",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "46304"
                        },
                        new
                        {
                            Id = 31,
                            City = "г Новосибирск",
                            Email = "Brandon.Schimmel87@gmail.com",
                            FirstName = "Алексей",
                            LastName = "Вирановская",
                            PhoneNumber = "79251390755",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "46304"
                        },
                        new
                        {
                            Id = 32,
                            City = "г Новосибирск",
                            Email = "Albina.Gleichner@hotmail.com",
                            FirstName = "Авгиння",
                            LastName = "Чунц",
                            PhoneNumber = "79175524506",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "30120"
                        },
                        new
                        {
                            Id = 33,
                            City = "г Новосибирск",
                            Email = "Alphonso.Dibbert@gmail.com",
                            FirstName = "Рамиль",
                            LastName = "Лебедев",
                            PhoneNumber = "79240552734",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "46304"
                        },
                        new
                        {
                            Id = 34,
                            City = "г Новосибирск",
                            Email = "Conner5@hotmail.com",
                            FirstName = "Рената",
                            LastName = "Железнов",
                            PhoneNumber = "79175524506",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "46304"
                        },
                        new
                        {
                            Id = 35,
                            City = "г Новосибирск",
                            Email = "Frederik.Hintz50@gmail.com",
                            FirstName = "Аза",
                            LastName = "Вирановская",
                            PhoneNumber = "79263258303",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "46304"
                        },
                        new
                        {
                            Id = 36,
                            City = "г Новосибирск",
                            Email = "Cullen_Wiegand22@gmail.com",
                            FirstName = "Мирослав",
                            LastName = "Лебедев",
                            PhoneNumber = "79236880618",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "48601"
                        },
                        new
                        {
                            Id = 37,
                            City = "г Новосибирск",
                            Email = "Ferne_Kuhlman@hotmail.com",
                            FirstName = "Михаил",
                            LastName = "Лебедев",
                            PhoneNumber = "79206398166",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "48601"
                        },
                        new
                        {
                            Id = 38,
                            City = "г Новосибирск",
                            Email = "Beryl.Thiel71@gmail.com",
                            FirstName = "Степан",
                            LastName = "Сыромятникова",
                            PhoneNumber = "79235970418",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "11791"
                        },
                        new
                        {
                            Id = 39,
                            City = "г Новосибирск",
                            Email = "Frankie.Sporer@yahoo.com",
                            FirstName = "Рената",
                            LastName = "Рязанов",
                            PhoneNumber = "79181521761",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "11791"
                        },
                        new
                        {
                            Id = 40,
                            City = "г Новосибирск",
                            Email = "Christa.Block@hotmail.com",
                            FirstName = "Дмитрий",
                            LastName = "Энтская",
                            PhoneNumber = "79170829045",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "11791"
                        },
                        new
                        {
                            Id = 41,
                            City = "г Новосибирск",
                            Email = "Christian_Kirlin47@yahoo.com",
                            FirstName = "Диана",
                            LastName = "Ягубова",
                            PhoneNumber = "79214604002",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "30120"
                        },
                        new
                        {
                            Id = 42,
                            City = "г Новосибирск",
                            Email = "Amya_Dicki@hotmail.com",
                            FirstName = "Абель",
                            LastName = "Поливанов",
                            PhoneNumber = "79240552734",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "30120"
                        },
                        new
                        {
                            Id = 43,
                            City = "г Новосибирск",
                            Email = "Esther.Anderson@hotmail.com",
                            FirstName = "Ильяс",
                            LastName = "Устимовича",
                            PhoneNumber = "79123838261",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "48601"
                        },
                        new
                        {
                            Id = 44,
                            City = "г Новосибирск",
                            Email = "Eve.Lind3@gmail.com",
                            FirstName = "Абрагина",
                            LastName = "Кучеров",
                            PhoneNumber = "79226596685",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "11791"
                        },
                        new
                        {
                            Id = 45,
                            City = "г Новосибирск",
                            Email = "Adriel87@hotmail.com",
                            FirstName = "Рамиль",
                            LastName = "Бурцев",
                            PhoneNumber = "79170829045",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "30120"
                        },
                        new
                        {
                            Id = 46,
                            City = "г Новосибирск",
                            Email = "Ezekiel.Kilback@gmail.com",
                            FirstName = "Абульфаза",
                            LastName = "Вирановская",
                            PhoneNumber = "79276075612",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "11791"
                        },
                        new
                        {
                            Id = 47,
                            City = "г Новосибирск",
                            Email = "Alexandra.Hudson95@yahoo.com",
                            FirstName = "Алан",
                            LastName = "Вирановская",
                            PhoneNumber = "79112864703",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "11791"
                        },
                        new
                        {
                            Id = 48,
                            City = "г Новосибирск",
                            Email = "Celestino96@gmail.com",
                            FirstName = "Аващарфа",
                            LastName = "Яковец",
                            PhoneNumber = "79166113768",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "48601"
                        },
                        new
                        {
                            Id = 49,
                            City = "г Новосибирск",
                            Email = "Ezekiel.Kilback@gmail.com",
                            FirstName = "Георгий",
                            LastName = "Зуева",
                            PhoneNumber = "79251390755",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "30120"
                        },
                        new
                        {
                            Id = 50,
                            City = "г Новосибирск",
                            Email = "Cassidy_Greenfelder10@hotmail.com",
                            FirstName = "Родион",
                            LastName = "Аверина",
                            PhoneNumber = "79249669496",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "11791"
                        },
                        new
                        {
                            Id = 51,
                            City = "г Новосибирск",
                            Email = "Arvel28@yahoo.com",
                            FirstName = "Глеб",
                            LastName = "Ельчуков",
                            PhoneNumber = "79175391429",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "46304"
                        },
                        new
                        {
                            Id = 52,
                            City = "г Новосибирск",
                            Email = "Brain.Gutkowski@hotmail.com",
                            FirstName = "Абдулька",
                            LastName = "Ягубова",
                            PhoneNumber = "79214604002",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "46304"
                        },
                        new
                        {
                            Id = 53,
                            City = "г Новосибирск",
                            Email = "Elroy.Harvey@gmail.com",
                            FirstName = "Аблялиль",
                            LastName = "Лапунова",
                            PhoneNumber = "79145224042",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "46304"
                        },
                        new
                        {
                            Id = 54,
                            City = "г Новосибирск",
                            Email = "Electa.Kris@yahoo.com",
                            FirstName = "Анатолий",
                            LastName = "Немцов",
                            PhoneNumber = "79182442818",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "46304"
                        },
                        new
                        {
                            Id = 55,
                            City = "г Новосибирск",
                            Email = "Billie_Ankunding61@yahoo.com",
                            FirstName = "Агния",
                            LastName = "Ермолаева",
                            PhoneNumber = "79301011718",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "46304"
                        },
                        new
                        {
                            Id = 56,
                            City = "г Новосибирск",
                            Email = "Christian_Kirlin47@yahoo.com",
                            FirstName = "Камиль",
                            LastName = "Немцов",
                            PhoneNumber = "79197853566",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "30120"
                        },
                        new
                        {
                            Id = 57,
                            City = "г Новосибирск",
                            Email = "Cristal_Dare97@gmail.com",
                            FirstName = "Доминика",
                            LastName = "Фамусов",
                            PhoneNumber = "79194399119",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "11791"
                        },
                        new
                        {
                            Id = 58,
                            City = "г Новосибирск",
                            Email = "Arnaldo14@gmail.com",
                            FirstName = "Семен",
                            LastName = "Бурцев",
                            PhoneNumber = "79274148070",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "46304"
                        },
                        new
                        {
                            Id = 59,
                            City = "г Новосибирск",
                            Email = "Edyth24@yahoo.com",
                            FirstName = "Абдупатта",
                            LastName = "Косыгина",
                            PhoneNumber = "79297956774",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "48601"
                        },
                        new
                        {
                            Id = 60,
                            City = "г Новосибирск",
                            Email = "Clifford23@hotmail.com",
                            FirstName = "Алексей",
                            LastName = "Антимонова",
                            PhoneNumber = "79147692876",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "48601"
                        },
                        new
                        {
                            Id = 61,
                            City = "г Новосибирск",
                            Email = "Anabelle_OConnell@hotmail.com",
                            FirstName = "Вадим",
                            LastName = "Сыромятникова",
                            PhoneNumber = "79177725196",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "30120"
                        },
                        new
                        {
                            Id = 62,
                            City = "г Новосибирск",
                            Email = "Bethel92@gmail.com",
                            FirstName = "Захар",
                            LastName = "Бурцева",
                            PhoneNumber = "79263258303",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "11791"
                        },
                        new
                        {
                            Id = 63,
                            City = "г Новосибирск",
                            Email = "Frankie.Sporer@yahoo.com",
                            FirstName = "Рената",
                            LastName = "Прудников",
                            PhoneNumber = "79261414348",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "48601"
                        },
                        new
                        {
                            Id = 64,
                            City = "г Новосибирск",
                            Email = "Dayna38@gmail.com",
                            FirstName = "Авагея",
                            LastName = "Яковец",
                            PhoneNumber = "79261414348",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "30120"
                        },
                        new
                        {
                            Id = 65,
                            City = "г Новосибирск",
                            Email = "Allie.Thompson24@gmail.com",
                            FirstName = "Артур",
                            LastName = "Крылов",
                            PhoneNumber = "79222998760",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "48601"
                        },
                        new
                        {
                            Id = 66,
                            City = "г Новосибирск",
                            Email = "Demarco_Schulist39@hotmail.com",
                            FirstName = "Сергей",
                            LastName = "Крылов",
                            PhoneNumber = "79122253313",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "30120"
                        },
                        new
                        {
                            Id = 67,
                            City = "г Новосибирск",
                            Email = "Anna24@hotmail.com",
                            FirstName = "Герман",
                            LastName = "Ялунина",
                            PhoneNumber = "79235970418",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "46304"
                        },
                        new
                        {
                            Id = 68,
                            City = "г Новосибирск",
                            Email = "Deron71@hotmail.com",
                            FirstName = "Роман",
                            LastName = "Железнов",
                            PhoneNumber = "79301115351",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "46304"
                        },
                        new
                        {
                            Id = 69,
                            City = "г Новосибирск",
                            Email = "Bonnie_Bode83@yahoo.com",
                            FirstName = "Агния",
                            LastName = "Булыгина",
                            PhoneNumber = "79251390755",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "30120"
                        },
                        new
                        {
                            Id = 70,
                            City = "г Новосибирск",
                            Email = "Abel_Rolfson38@gmail.com",
                            FirstName = "Георгий",
                            LastName = "Косыгина",
                            PhoneNumber = "79274932037",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "30120"
                        },
                        new
                        {
                            Id = 71,
                            City = "г Новосибирск",
                            Email = "Barton_Labadie@yahoo.com",
                            FirstName = "Артем",
                            LastName = "Крылов",
                            PhoneNumber = "79248643064",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "11791"
                        },
                        new
                        {
                            Id = 72,
                            City = "г Новосибирск",
                            Email = "Anabelle_OConnell@hotmail.com",
                            FirstName = "Августиния",
                            LastName = "Авилова",
                            PhoneNumber = "79249669496",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "46304"
                        },
                        new
                        {
                            Id = 73,
                            City = "г Новосибирск",
                            Email = "Chance_Blanda74@hotmail.com",
                            FirstName = "Алексей",
                            LastName = "Поливанов",
                            PhoneNumber = "79199629371",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "48601"
                        },
                        new
                        {
                            Id = 74,
                            City = "г Новосибирск",
                            Email = "Barton_Labadie@yahoo.com",
                            FirstName = "Авагея",
                            LastName = "Бурцев",
                            PhoneNumber = "79211394433",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "30120"
                        },
                        new
                        {
                            Id = 75,
                            City = "г Новосибирск",
                            Email = "Elroy.Harvey@gmail.com",
                            FirstName = "Абдурасуль",
                            LastName = "Бархотов",
                            PhoneNumber = "73832035454",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "30120"
                        },
                        new
                        {
                            Id = 76,
                            City = "г Новосибирск",
                            Email = "Corrine_Toy@hotmail.com",
                            FirstName = "Анатолий",
                            LastName = "Кучеров",
                            PhoneNumber = "79227798846",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "46304"
                        },
                        new
                        {
                            Id = 77,
                            City = "г Новосибирск",
                            Email = "Christa.Block@hotmail.com",
                            FirstName = "Лев",
                            LastName = "Дубинкин",
                            PhoneNumber = "79263258303",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "11791"
                        },
                        new
                        {
                            Id = 78,
                            City = "г Новосибирск",
                            Email = "Adam9@hotmail.com",
                            FirstName = "Клим",
                            LastName = "Ямковой",
                            PhoneNumber = "79228800561",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "48601"
                        },
                        new
                        {
                            Id = 79,
                            City = "г Новосибирск",
                            Email = "Annabel11@hotmail.com",
                            FirstName = "Владимир",
                            LastName = "Козлитин",
                            PhoneNumber = "79256060675",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "30120"
                        },
                        new
                        {
                            Id = 80,
                            City = "г Новосибирск",
                            Email = "Albina.Gleichner@hotmail.com",
                            FirstName = "Артемий",
                            LastName = "Косыгина",
                            PhoneNumber = "79118006386",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "48601"
                        },
                        new
                        {
                            Id = 81,
                            City = "г Новосибирск",
                            Email = "Cecile.Herman8@hotmail.com",
                            FirstName = "Абика",
                            LastName = "Кондр",
                            PhoneNumber = "79298189796",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "30120"
                        },
                        new
                        {
                            Id = 82,
                            City = "г Новосибирск",
                            Email = "Elza_Gislason92@gmail.com",
                            FirstName = "Марк",
                            LastName = "Энтская",
                            PhoneNumber = "79274148070",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "48601"
                        },
                        new
                        {
                            Id = 83,
                            City = "г Новосибирск",
                            Email = "Daphnee.Huels30@gmail.com",
                            FirstName = "Роман",
                            LastName = "Лукьяненко",
                            PhoneNumber = "79175524506",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "48601"
                        },
                        new
                        {
                            Id = 84,
                            City = "г Новосибирск",
                            Email = "Eloise_Casper@hotmail.com",
                            FirstName = "Макар",
                            LastName = "Авилова",
                            PhoneNumber = "79240552734",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "11791"
                        },
                        new
                        {
                            Id = 85,
                            City = "г Новосибирск",
                            Email = "Christa.Block@hotmail.com",
                            FirstName = "Матвей",
                            LastName = "Коченков",
                            PhoneNumber = "79132558821",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "48601"
                        },
                        new
                        {
                            Id = 86,
                            City = "г Новосибирск",
                            Email = "Etha.Hoppe79@gmail.com",
                            FirstName = "Степан",
                            LastName = "Майструк",
                            PhoneNumber = "79280809296",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "30120"
                        },
                        new
                        {
                            Id = 87,
                            City = "г Новосибирск",
                            Email = "Edyth24@yahoo.com",
                            FirstName = "Аблялиль",
                            LastName = "Сыромятникова",
                            PhoneNumber = "79151332992",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "46304"
                        },
                        new
                        {
                            Id = 88,
                            City = "г Новосибирск",
                            Email = "Camron.Goldner@hotmail.com",
                            FirstName = "Абраша",
                            LastName = "Ельчуков",
                            PhoneNumber = "79170829045",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "30120"
                        },
                        new
                        {
                            Id = 89,
                            City = "г Новосибирск",
                            Email = "Eldred_Stark10@gmail.com",
                            FirstName = "Руслан",
                            LastName = "Давыдкина",
                            PhoneNumber = "79209052714",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "48601"
                        },
                        new
                        {
                            Id = 90,
                            City = "г Новосибирск",
                            Email = "Cullen_Wiegand22@gmail.com",
                            FirstName = "Петр",
                            LastName = "Казак",
                            PhoneNumber = "79177725196",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "30120"
                        },
                        new
                        {
                            Id = 91,
                            City = "г Новосибирск",
                            Email = "Demarco_Schulist39@hotmail.com",
                            FirstName = "Прохор",
                            LastName = "Поливанов",
                            PhoneNumber = "79139023581",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "48601"
                        },
                        new
                        {
                            Id = 92,
                            City = "г Новосибирск",
                            Email = "Colt_Kozey83@gmail.com",
                            FirstName = "Марсель",
                            LastName = "Ялунина",
                            PhoneNumber = "79194399119",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "11791"
                        },
                        new
                        {
                            Id = 93,
                            City = "г Новосибирск",
                            Email = "Freddie62@gmail.com",
                            FirstName = "Арсен",
                            LastName = "Жикина",
                            PhoneNumber = "79105325941",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "30120"
                        },
                        new
                        {
                            Id = 94,
                            City = "г Новосибирск",
                            Email = "Daisy.Hansen@gmail.com",
                            FirstName = "Богдан",
                            LastName = "Энтская",
                            PhoneNumber = "79280809296",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "30120"
                        },
                        new
                        {
                            Id = 95,
                            City = "г Новосибирск",
                            Email = "Conner5@hotmail.com",
                            FirstName = "Римма",
                            LastName = "Фамусов",
                            PhoneNumber = "79222586517",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "48601"
                        },
                        new
                        {
                            Id = 96,
                            City = "г Новосибирск",
                            Email = "Freddie62@gmail.com",
                            FirstName = "Аанжелла",
                            LastName = "Ельцина",
                            PhoneNumber = "79293409930",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "11791"
                        },
                        new
                        {
                            Id = 97,
                            City = "г Новосибирск",
                            Email = "Colt_Kozey83@gmail.com",
                            FirstName = "Антон",
                            LastName = "Берия",
                            PhoneNumber = "79166113768",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "46304"
                        },
                        new
                        {
                            Id = 98,
                            City = "г Новосибирск",
                            Email = "Annabel11@hotmail.com",
                            FirstName = "Всеволод",
                            LastName = "Дюкова",
                            PhoneNumber = "79175391429",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "48601"
                        },
                        new
                        {
                            Id = 99,
                            City = "г Новосибирск",
                            Email = "Evert_Schaefer@gmail.com",
                            FirstName = "Василий",
                            LastName = "Ягубова",
                            PhoneNumber = "79139023581",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "48601"
                        },
                        new
                        {
                            Id = 100,
                            City = "г Новосибирск",
                            Email = "Dayna38@gmail.com",
                            FirstName = "Валентин",
                            LastName = "Ямковой",
                            PhoneNumber = "79261414348",
                            StreetAddress = "17 Bromwell Street",
                            ZipCode = "48601"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
