using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Person.Model.EntityConfig
{
    public class PersonTypeConfiguration : IEntityTypeConfiguration<Entity.Person>
    {
        public void Configure(EntityTypeBuilder<Entity.Person> builder)
        {
            builder.ToTable("Person");

            var data = new List<Entity.Person>();
            for (int i = 1; i <= 100; i++)
            {
                data.Add(new Entity.Person
                {
                    Id = i,
                    FirstName = GetRandom(Data.FirstNames),
                    LastName = GetRandom(Data.LastNames),
                    PhoneNumber = GetRandom(Data.PhoneNumber),
                    ZipCode = GetRandom(Data.ZipCode),
                    City = "г Новосибирск",
                    Email = GetRandom(Data.Email),
                    StreetAddress = GetRandom(Data.Address)
                });
            }

            builder.HasData(data);
        }

        public static string GetRandom(string[] src)
        {
            var rd = new Random();
            var index = rd.Next(0, src.Length - 1);

            return src[index].TrimEnd(' ');
        }
    }

    internal class Data
    {
        public static string[] FirstNames = new[]
        {
            "Аалия          ",
            "Аанжелла       ",
            "Аба            ",
            "Абав           ",
            "Абам           ",
            "Абаханум       ",
            "Абаш           ",
            "Аббаза         ",
            "Абгюль         ",
            "Абдужалия      ",
            "Абдулния       ",
            "Абдулпетта     ",
            "Абдулька       ",
            "Абдупатта      ",
            "Абдурасуль     ",
            "Абдурефи       ",
            "Абдурома       ",
            "Абдюль         ",
            "Абелина        ",
            "Абель          ",
            "Абибат         ",
            "Абигель        ",
            "Абика          ",
            "Абилфетта      ",
            "Аблялиль       ",
            "Абрагина       ",
            "Абрамия        ",
            "Абраша         ",
            "Абрииа         ",
            "Абуватфа       ",
            "Абульфаза      ",
            "Абуся          ",
            "Абута          ",
            "Абутаима       ",
            "Авагея         ",
            "Аванда         ",
            "Аванна         ",
            "Авашарфа       ",
            "Авашерфа       ",
            "Аващарфа       ",
            "Авгалифена     ",
            "Авгела         ",
            "Авгения        ",
            "Авгиння        ",
            "Авгусита       ",
            "Августа        ",
            "Августина      ",
            "Августиния     ",
            "Авдия          ",
            "Авдокия        ",
            "Авдоля         ",
            "Агния          ",
            "Аза            ",
            "Алан           ",
            "Александр      ",
            "Алексей        ",
            "Альберт        ",
            "Анастасия      ",
            "Анатолий       ",
            "Андрей         ",
            "Антон          ",
            "Антонина       ",
            "Анфиса         ",
            "Ариадна        ",
            "Арсен          ",
            "Арсений        ",
            "Артем          ",
            "Артемий        ",
            "Артур          ",
            "Богдан         ",
            "Борис          ",
            "Вадим          ",
            "Валентин       ",
            "Валерий        ",
            "Василий        ",
            "Вероника       ",
            "Виталий        ",
            "Владимир       ",
            "Владислав      ",
            "Всеволод       ",
            "Всеслава       ",
            "Вячеслав       ",
            "Галина         ",
            "Геннадий       ",
            "Георгий        ",
            "Герман         ",
            "Глеб           ",
            "Гордей         ",
            "Григорий       ",
            "Давид          ",
            "Дамир          ",
            "Даниил         ",
            "Демид          ",
            "Демьян         ",
            "Денис          ",
            "Диана          ",
            "Дмитрий        ",
            "Доминика       ",
            "Ева            ",
            "Евгений        ",
            "Евдокия        ",
            "Егор           ",
            "Елисей         ",
            "Ефросинья      ",
            "Захар          ",
            "Зинаида        ",
            "Иван           ",
            "Игнат          ",
            "Илья           ",
            "Ильяс          ",
            "Ирина          ",
            "Камиль         ",
            "Карим          ",
            "Кирилл         ",
            "Клим           ",
            "Константин     ",
            "Лев            ",
            "Леонид         ",
            "Лидия          ",
            "Любовь         ",
            "Майя           ",
            "Макар          ",
            "Максим         ",
            "Марат          ",
            "Марианна       ",
            "Марк           ",
            "Марсель        ",
            "Матвей         ",
            "Мирон          ",
            "Мирослав       ",
            "Михаил         ",
            "Назар          ",
            "Никита         ",
            "Николай        ",
            "Нона           ",
            "Олег           ",
            "Ольга          ",
            "Павел          ",
            "Пелагея        ",
            "Петр           ",
            "Платон         ",
            "Прохор         ",
            "Рамиль         ",
            "Ратмир         ",
            "Рената         ",
            "Римма          ",
            "Ринат          ",
            "Роберт         ",
            "Родион         ",
            "Роман          ",
            "Ростислав      ",
            "Руслан         ",
            "Рустам         ",
            "Савва          ",
            "Савелий        ",
            "Святослав      ",
            "Семен          ",
            "Сергей         ",
            "Станислав      ",
            "Степан         ",
            "Эвелина        ",
            "Эльвира        ",
            "Яна            "
        };

        public static string[] LastNames = new[]
        {
            "Аверина            ",
            "Авилова            ",
            "Антимонова         ",
            "Бархотов           ",
            "Берия              ",
            "Богоявленская      ",
            "Бортник            ",
            "Булыгина           ",
            "Бурцев             ",
            "Бурцева            ",
            "Вирановская        ",
            "Давыдкина          ",
            "Данильцина         ",
            "Дубинкин           ",
            "Дюкова             ",
            "Елагин             ",
            "Ельцина            ",
            "Ельчуков           ",
            "Ермолаева          ",
            "Жарыхин            ",
            "Железнов           ",
            "Жикина             ",
            "Жуков              ",
            "Зубов              ",
            "Зубова             ",
            "Зуева              ",
            "Казак              ",
            "Козлитин           ",
            "Койтасбаева        ",
            "Кондр              ",
            "Коржуков           ",
            "Косыгина           ",
            "Коченков           ",
            "Кравчиков          ",
            "Крылов             ",
            "Кучеров            ",
            "Лапунова           ",
            "Лебедев            ",
            "Лукашенко          ",
            "Лукьяненко         ",
            "Майструк           ",
            "Немцов             ",
            "Поливанов          ",
            "Прудников          ",
            "Рыжова             ",
            "Рязанов            ",
            "Смехова            ",
            "Старостин          ",
            "Сыромятникова      ",
            "Тотенков           ",
            "Устимовича         ",
            "Устиновича         ",
            "Фамусов            ",
            "Чигракова          ",
            "Чунц               ",
            "Энгельгардт        ",
            "Энтская            ",
            "Ягубова            ",
            "Яковец             ",
            "Ялунина            ",
            "Ямковой            ",
            "Янович             "
        };

        public static string[] Email = new[]
        {
            "Abbie89@gmail.com                       ",
            "Abel_Rolfson38@gmail.com               ",
            "Adam9@hotmail.com                      ",
            "Adrian.Smith65@gmail.com               ",
            "Adriel87@hotmail.com                   ",
            "Albina.Gleichner@hotmail.com           ",
            "Alexandra.Hudson95@yahoo.com           ",
            "Alfonzo.Howell24@hotmail.com           ",
            "Alison94@hotmail.com                   ",
            "Aliya53@gmail.com                      ",
            "Allie.Thompson24@gmail.com             ",
            "Allie42@gmail.com                      ",
            "Alphonso.Dibbert@gmail.com             ",
            "Amya_Dicki@hotmail.com                 ",
            "Anabelle_OConnell@hotmail.com          ",
            "Anderson_Huels@gmail.com               ",
            "Anna24@hotmail.com                     ",
            "Annabel11@hotmail.com                  ",
            "Arnaldo14@gmail.com                    ",
            "Arvel28@yahoo.com                      ",
            "Arvid_McGlynn55@gmail.com              ",
            "Barton_Labadie@yahoo.com               ",
            "Benedict97@yahoo.com                   ",
            "Beryl.Thiel71@gmail.com                ",
            "Bethany62@gmail.com                    ",
            "Bethel92@gmail.com                     ",
            "Billie_Ankunding61@yahoo.com           ",
            "Bonnie_Bode83@yahoo.com                ",
            "Brain.Gutkowski@hotmail.com            ",
            "Brandon.Schimmel87@gmail.com           ",
            "Breanne.Greenfelder85@hotmail.com      ",
            "Brett.Wyman@hotmail.com                ",
            "Bridie_Wyman34@hotmail.com             ",
            "Brook.Robel21@gmail.com                ",
            "Camilla42@gmail.com                    ",
            "Camron.Goldner@hotmail.com             ",
            "Camryn29@gmail.com                     ",
            "Carolanne21@hotmail.com                ",
            "Cassidy_Greenfelder10@hotmail.com      ",
            "Cathryn_Halvorson82@hotmail.com        ",
            "Cecil.Dickinson@gmail.com              ",
            "Cecil.Johns8@hotmail.com               ",
            "Cecile.Herman8@hotmail.com             ",
            "Celestino96@gmail.com                  ",
            "Chance_Blanda74@hotmail.com            ",
            "Christa.Block@hotmail.com              ",
            "Christian_Kirlin47@yahoo.com           ",
            "Claire.Daugherty@yahoo.com             ",
            "Clarabelle66@gmail.com                 ",
            "Claudia58@gmail.com                    ",
            "Clifford23@hotmail.com                 ",
            "Colin.Ferry@yahoo.com                  ",
            "Colt_Kozey83@gmail.com                 ",
            "Conner5@hotmail.com                    ",
            "Corine_White98@hotmail.com             ",
            "Corrine_Toy@hotmail.com                ",
            "Cristal_Dare97@gmail.com               ",
            "Cullen_Wiegand22@gmail.com             ",
            "Daisy.Hansen@gmail.com                 ",
            "Dakota34@hotmail.com                   ",
            "Dale.Kunze48@yahoo.com                 ",
            "Danial.Raynor91@gmail.com              ",
            "Daniella22@yahoo.com                   ",
            "Daphnee.Huels30@gmail.com              ",
            "Dayna38@gmail.com                      ",
            "Demarco_Schulist39@hotmail.com         ",
            "Deon_Armstrong@yahoo.com               ",
            "Deron71@hotmail.com                    ",
            "Derrick.Koelpin@yahoo.com              ",
            "Dessie9@hotmail.com                    ",
            "Domingo_Prosacco89@gmail.com           ",
            "Don_Maggio@hotmail.com                 ",
            "Ed_Lesch52@yahoo.com                   ",
            "Edyth24@yahoo.com                      ",
            "Eldred_Stark10@gmail.com               ",
            "Electa.Kris@yahoo.com                  ",
            "Electa8@yahoo.com                      ",
            "Eloise_Casper@hotmail.com              ",
            "Elroy.Harvey@gmail.com                 ",
            "Elza_Gislason92@gmail.com              ",
            "Emely_Turcotte@yahoo.com               ",
            "Emery.Homenick@yahoo.com               ",
            "Emery_Kreiger@gmail.com                ",
            "Emilio98@gmail.com                     ",
            "Eriberto.Schinner@gmail.com            ",
            "Ernie.Wyman58@hotmail.com              ",
            "Esther.Anderson@hotmail.com            ",
            "Etha.Hoppe79@gmail.com                 ",
            "Eve.Lind3@gmail.com                    ",
            "Evert_Schaefer@gmail.com               ",
            "Evie_Mertz@gmail.com                   ",
            "Ezekiel.Kilback@gmail.com              ",
            "Fernando.Goyette@hotmail.com           ",
            "Ferne_Kuhlman@hotmail.com              ",
            "Fleta85@hotmail.com                    ",
            "Frankie.Effertz44@hotmail.com          ",
            "Frankie.Sporer@yahoo.com               ",
            "Freddie62@gmail.com                    ",
            "Frederik.Hintz50@gmail.com             ",
            "Frederik27@yahoo.com                   "
        };

        public static string[] PhoneNumber = new[]
        {
                "73832035454",
                "79105325941",
                "79106585034",
                "79108738274",
                "79112864703",
                "79116488841",
                "79118006386",
                "79122253313",
                "79122763965",
                "79123838261",
                "79124496807",
                "79132558821",
                "79135019122",
                "79135453084",
                "79136963602",
                "79139023581",
                "79139604008",
                "79140179549",
                "79141440613",
                "79141533099",
                "79145224042",
                "79147692876",
                "79150056116",
                "79151332992",
                "79151804636",
                "79152254604",
                "79153536338",
                "79163205719",
                "79166113768",
                "79167447610",
                "79170829045",
                "79174972512",
                "79175391429",
                "79175524506",
                "79177725196",
                "79181521761",
                "79182442818",
                "79185574147",
                "79188438964",
                "79193525322",
                "79194399119",
                "79195668227",
                "79197853566",
                "79199629371",
                "79200583960",
                "79202142269",
                "79205944708",
                "79206112248",
                "79206398166",
                "79209052714",
                "79211394433",
                "79214483093",
                "79214604002",
                "79222586517",
                "79222998760",
                "79226596685",
                "79227798846",
                "79228800561",
                "79231465408",
                "79233641458",
                "79235970418",
                "79236880618",
                "79240552734",
                "79248643064",
                "79249669496",
                "79251390755",
                "79256060675",
                "79257500760",
                "79257918487",
                "79261414348",
                "79263258303",
                "79274148070",
                "79274932037",
                "79276075612",
                "79280809296",
                "79289000976",
                "79291784876",
                "79293409930",
                "79297956774",
                "79298189796",
                "79301011718",
                "79301115351",
                "79301262016",
                "79309608485"
        };

        public static string[] Address = new[]
        {
            "17 Bromwell Street",
            "243 High Level Road"
        };

        public static string[] ZipCode = new[]
        {
            "46304",
            "11791",
            "30120",
            "48601",
            "36605"
        };
    }
}